spring:
  application:
    name: bikePartsHub

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: 8080

paypal:
  client-id: ${PAYPAL_CLIENT_ID}
  client-secret: ${PAYPAL_CLIENT_SECRET}
  mode: sandbox # use 'sandbox' for testing and 'live' for production

s3bucket:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret: ${AWS_SECRET_ACCESS_KEY}
  bucket-name: ${AWS_S3_BUCKET_NAME}
  region: ${AWS_REGION:us-east-1}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 166400000 # 7 days
