name: Build, Push and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/bikePartsHub
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bikepartshub-backend:latest
      
      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/BikePartsHubApp
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bikepartshub-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            # Pull the latest images
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/bikepartshub-backend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/bikepartshub-frontend:latest
            
            # Stop and remove existing containers if they exist
            docker stop bikepartshub-backend || true
            docker stop bikepartshub-frontend || true
            docker rm bikepartshub-backend || true
            docker rm bikepartshub-frontend || true
            
            # Run new containers
            docker run -d --name bikepartshub-backend -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/bikepartshub-backend:latest
            docker run -d --name bikepartshub-frontend -p 80:4200 ${{ secrets.DOCKERHUB_USERNAME }}/bikepartshub-frontend:latest
            
            # Clean up unused images
            docker system prune -af
